language: node_js
node_js:
  - 12.18.3

branches:
  only:
  - main

services:
  docker

script:
  - docker --version
  - docker build -t udagram-reverse-proxy .
  - docker tag udagram-reverse-proxy elsrickle/udagram-reverse-proxy:latest

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elsrickle/udagram-reverse-proxy